FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Controllers/OrgnizationController.cs
using HiringWeb.Core.DTO;
using HiringWeb.Core.ViewModels;
using HiringWeb.Services.NotificationsOperations;
using HiringWeb.Services.OrgnizationOperations;
using HiringWeb.Services.UserOperations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Hiring.Web_FinalProject_VisionPlus_ASP.NetCore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrgnizationController : BaseController
    {
        private readonly IOrgnizationServices _OrgServices;

        public OrgnizationController(IOrgnizationServices OrgServices,
            IUserServices UserOperation, INotificationServices INotificationServices) : base(UserOperation, INotificationServices)
        {
            _OrgServices = OrgServices;
        }
        
        public async Task<IActionResult> Index(int Id, string SearchWord, int SelectSize)
        {
            var AllOrg = await _OrgServices.Index(Id, SearchWord, SelectSize);
            ViewBag.SearchWord = SearchWord;
            ViewBag.SelectSize = SelectSize;
            return View(AllOrg);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var users = await _OrgServices.AddGet();
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ErrorOrgnizeAdd SetOrg, IFormFile ProfileImage)
        {
            //Save Image(File) In DB
            if (ProfileImage != null)
            {
                using (var fileStore = new MemoryStream())
                {
                    await ProfileImage.CopyToAsync(fileStore);
                    SetOrg.OrgnizationAddDto.ProfileImgUser = fileStore.ToArray();
                }
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            var ResultAdd = await _OrgServices.Add(SetOrg.OrgnizationAddDto, userId);
            if(ResultAdd.IsFalid == false)
            {
                //ViewBag.ResError = ResultAdd.ResultError;
                TempData["ResError"] = $"e: {ResultAdd.ResultError}";

                return View(SetOrg);
            }
            TempData["ResError"] = $"s: لقد تم إضافة الشركة بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var GetModel = await _OrgServices.EditGet(Id);
            if (!GetModel.IsFalid)
            {
                return NotFound();
            }
            return View(GetModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ErrorOrgnizeEdit EditOrg, IFormFile ProfileImage)
        {
            //Save Image(File) In DB
            if (ProfileImage != null)
            {
                using (var fileStore = new MemoryStream())
                {
                    await ProfileImage.CopyToAsync(fileStore);
                    EditOrg.OrgnizationEditDto.ProfileImgUser = fileStore.ToArray();
                }
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId

            var SetModel = await _OrgServices.EditPost(EditOrg.OrgnizationEditDto, userId);
            if (!SetModel.IsFalid)
            {
                //ViewBag.ResError = SetModel.ResultError;
                TempData["ResError"] = $"e: {SetModel.ResultError}";
                return View(SetModel);
            }
            TempData["ResError"] = $"s: لقد تم تعديل بيانات الشركة بنجاح.";

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var GetOrg = await _OrgServices.ReturnOrgnization(Id);
            var OrgDel = await _OrgServices.Delete(Id);
            if(OrgDel == false)
            {
                return NotFound();
            }
            //TempData["SuccessDel"] = "لقد تم حذف شركة/ "+ GetOrg.Name + " ومديرها المستخدم / " + GetOrg.User.FullName;
            TempData["ResError"] = $"s: لقد تم حذف شركة / {GetOrg.Name} ومديرها المستخدم / {GetOrg.User.FullName} بنجاح.";
            return RedirectToAction(nameof(Index));
        }
    }
}

FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Controllers/RoleController.cs
using HiringWeb.Core.DTO;
using HiringWeb.Core.ViewModels;
using HiringWeb.Services.NotificationsOperations;
using HiringWeb.Services.RoleOperations;
using HiringWeb.Services.UserOperations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hiring.Web_FinalProject_VisionPlus_ASP.NetCore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : BaseController
    {
        private readonly IRoleServices _RoleServices;

        public RoleController(IRoleServices RoleServices,
            IUserServices UserOperation, INotificationServices INotificationServices) : base(UserOperation, INotificationServices)
        {
            _RoleServices = RoleServices;
        }

        public async Task<IActionResult> Index()
        {
            var Roles = await _RoleServices.Index(); 
            return View(Roles);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(RoleAddDto role)
        {
            await _RoleServices.Add(role);
            TempData["ResError"] = "s: لقد تم إضافة الصلاحية بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {
            return View(await _RoleServices.EditGet(Id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleEditDto role)
        {
            await _RoleServices.EditPost(role);
            TempData["ResError"] = "s: لقد تم تعديل الصلاحية بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string Id)
        {
           await _RoleServices.Delete(Id);
            TempData["ResError"] = "s: لقد تم حذف الصلاحية بنجاح.";
            return RedirectToAction(nameof(Index));
        }

    }
}

FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Controllers/UserController.cs
using AutoMapper;
using HiringWeb.Core.DTO;
using HiringWeb.Core.ViewModels;
using HiringWeb.DataBase.Models;
using HiringWeb.Services.NotificationsOperations;
using HiringWeb.Services.OrgnizationOperations;
using HiringWeb.Services.UserOperations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Hiring.Web_FinalProject_VisionPlus_ASP.NetCore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : BaseController
    {
        private readonly IUserServices _IUserServices;
        private readonly IOrgnizationServices _OrgServices;
        private readonly IMapper _Mapper;
        private readonly SignInManager<UserApplication> _SignInManager;



        public UserController(IUserServices IUserServices,
                              IOrgnizationServices OrgServices,
                              SignInManager<UserApplication> SignInManager,
                              IMapper Mapper, IUserServices UserOperation,
                              INotificationServices INotificationServices) : base(UserOperation, INotificationServices)
        {
            _IUserServices = IUserServices;
            _OrgServices = OrgServices;
            _Mapper = Mapper;
            _SignInManager = SignInManager;
        }
        public async Task<IActionResult> Index(int Id, string SearchWord, int SelectSize)
        {
            var AllUser = await _IUserServices.Index(Id, SearchWord, SelectSize);
            ViewBag.SearchWord = SearchWord;
            ViewBag.SelectSize = SelectSize;
            return View(AllUser);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var users = await _IUserServices.AddGet();
            return View(users);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Add([FromForm] ErrorUserAddPostViewModel model, IFormFile ProfileImage)
        {
            //Save Image(File) In DB
            if (ProfileImage != null)
            {
                using (var fileStore = new MemoryStream())
                {
                    await ProfileImage.CopyToAsync(fileStore);
                    model.UserCreateDto.ProfileImgUser = fileStore.ToArray();
                }
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            var SentModel = await _IUserServices.AddPost(model.UserCreateDto, userId);
            if (!SentModel.IsFalid)
            {
                //ViewBag.ResError = SentModel.ResultError;
                TempData["ResError"] = $"e: {SentModel.ResultError}";
                return View(SentModel);
            }
            TempData["ResError"] = $"s: لقد تم إضافة المستخدم بنجاح.";
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                // To SingnIn User After register And Return Home Page With Login
               await _SignInManager
              .PasswordSignInAsync(model.UserCreateDto.Email, model.UserCreateDto.Password, false, false);
                return Redirect("~/Home/Index");
            }

        }

        [HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {
            var GetModel = await _IUserServices.EditGet(Id);
            if (!GetModel.IsFalid)
            {
                return NotFound();
            }
            return View(GetModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] ErrorUserAddPostViewModel model, IFormFile ProfileImage)
        {
            ErrorOrgnizeEdit ModelOrg = new ErrorOrgnizeEdit();
            ErrorUserAddPostViewModel ModelUser = new ErrorUserAddPostViewModel();
            if (ProfileImage != null)
            {
                using (var fileStore = new MemoryStream())
                {
                    await ProfileImage.CopyToAsync(fileStore);
                    model.UserCreateDto.ProfileImgUser = fileStore.ToArray();
                }
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId

            if (model.UserCreateDto.NumOrgnization != null)
            {
                var NewModel = new OrgnizationEditDto
                {
                    Email = model.UserCreateDto.Email,
                    FullName = model.UserCreateDto.FullName,
                    ProfileImgUser = model.UserCreateDto.ProfileImgUser,
                    PhoneNumber = model.UserCreateDto.PhoneNumber,
                    AllRoles = model.UserCreateDto.AllRoles,
                    Id = (int)model.UserCreateDto.NumOrgnization
                };
                ModelOrg = await _OrgServices.EditPost(NewModel, userId);
                ModelUser.IsFalid = true;
            }
            else
            {
                ModelUser = await _IUserServices.EditPost(model.UserCreateDto, userId);
                ModelOrg.IsFalid = true;
            }


            if (!ModelOrg.IsFalid)
            {
                //ViewBag.ResError = ModelOrg.ResultError;
                TempData["ResError"] = $"e: {ModelOrg.ResultError}";
                return View(ModelOrg);
            }
            else if (!ModelUser.IsFalid)
            {
                //ViewBag.ResError = ModelOrg.ResultError;
                TempData["ResError"] = $"e: {ModelUser.ResultError}";

                return View(ModelUser);
            }

            TempData["ResError"] = $"s: لقد تم تعديل المستخدم بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string Id)
        {
            var GetUser = await _IUserServices.ReturnUser(Id);
            if (GetUser.NumOrgnization != null)
            {
                TempData["ResError"] = $"e:عزيزي لا يمكن حذف هذا المستخدم لأنه مدير شركة، يجب حذف شركته ثم حذفه!";
                return RedirectToAction(nameof(Index));
            }


            var SetModel = await _IUserServices.Delete(Id);
            if (!SetModel.IsValid)
            {
                return NotFound();
            }
            TempData["ResError"] = "s:لقد تم حذف المستخدم بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Excel()
        {
            var content = await _IUserServices.ToExcel();

            return File(
               content,
               "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
               $"{"report"}-{DateTime.Now:d}.xlsx"
           );
        }



    }
}

FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hiring.Web_FinalProject_VisionPlus_ASP.NetCore</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet"
          href="https://cdn.rtlcss.com/bootstrap/v4.3.1/css/bootstrap.min.css"
          integrity="sha384-LobEUEN+vN9RjeqoGV210e9rydU8P3KMTgX9FKxalf0zavDGgINz6K+iXoTLpNFA"
          crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/StyleWeb.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">موقع التوظيف</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">الرئيسية</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">السياسات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">الصلاحيات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">المستخدمين</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orgnization" asp-action="Index">الشركات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HiringOrder" asp-action="Index">طلبات التقدم</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="Webfooter border-top footer text-muted">
        <div class="container">
            حقوق النشر محفوظة لصالح موقع التوظيف &copy; 2021
        </div>
    </footer>
    @*CKEditor Js*@
    <script src="//cdn.ckeditor.com/4.16.2/full/ckeditor.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>