FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Controllers/HiringOrderController.cs
using HiringWeb.Core.DTO;
using HiringWeb.Core.Enums;
using HiringWeb.Core.ViewModels;
using HiringWeb.Services.EmailOperation;
using HiringWeb.Services.HiringOrderOperations;
using HiringWeb.Services.NotificationsOperations;
using HiringWeb.Services.UserOperations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Hiring.Web_FinalProject_VisionPlus_ASP.NetCore.Controllers
{
    [Authorize]
    public class HiringOrderController : BaseController
    {
        private readonly IHiringOrderService _HiringOrderService;
        private readonly ISendMailServices _SendMailServices;
        private readonly IUserServices _IUserServices;

        public HiringOrderController(IHiringOrderService HiringOrderService, 
            ISendMailServices SendMailServices, IUserServices UserOperation,
            IUserServices IUserServices, INotificationServices INotificationServices) : base(UserOperation, INotificationServices)
        {
            _HiringOrderService = HiringOrderService;
            _SendMailServices = SendMailServices;
            _IUserServices = IUserServices;
        }

        public async Task<IActionResult> Index(int Id, string SearchWord, int SelectSize,
                                                StatusHiringOrderEnum StatusOrder)
        {
            var CurrentUser = await _IUserServices.ReturnUser(UserId);
            var AllHiringOrd = await _HiringOrderService.Index(Id, SearchWord, SelectSize, StatusOrder, CurrentUser);
            ViewBag.SearchWord = SearchWord;
            ViewBag.SelectSize = SelectSize;
            ViewBag.StatusOrder = StatusOrder;
            return View(AllHiringOrd);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            ViewData["AllOrg"] = await _HiringOrderService.AddGet();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add([FromForm]HiringOrderAddDto model)
        {
            if(!ModelState.IsValid)
            {
                 ModelState.AddModelError("Description", "هذا الحقل مطلوب");
                ViewData["AllOrg"] = await _HiringOrderService.AddGet();
                return View();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            var ResultAdd = await _HiringOrderService.AddPost(model, userId);
            if (!ResultAdd)
            {
                //ViewBag.ResError = "لم يتم إضافة الطلب بنجاح يرجى التأكد من البيانات المدخلة";
                TempData["ResError"] = "e: لم يتم إضافة الطلب بنجاح يرجى التأكد من البيانات المدخلة!";
                return View(model);
            }
            TempData["ResError"] = "s: لقد تم إضافة الطلب بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var GetModel = await _HiringOrderService.EditGet(Id);
            if (GetModel == null)
            {
                return NotFound();
            }
            ViewData["AllOrg"] = await _HiringOrderService.AddGet();
            return View(GetModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(HiringOrderEditDto model)
        {
         
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId

            var SetModel = await _HiringOrderService.EditPost(model, userId);
            if (!SetModel)
            {
                //ViewBag.ResError = "لم يتم تعديل الطلب بنجاح يرجى التأكد من البيانات المدخلة";
                TempData["ResError"] = "e: لم يتم تعديل الطلب بنجاح يرجى التأكد من البيانات المدخلة";
                return View(model);
            }
            TempData["ResError"] = "s: لقد تم تعديل الطلب بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int Id)
        {
            var GetOrder = await _HiringOrderService.Details(Id);
            return View(GetOrder);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var OrderDel = await _HiringOrderService.Delete(Id);
            if (!OrderDel)
            {
                return NotFound();
            }
            TempData["ResError"] = "s: لقد تم حذف الطلب بنجاح.";

            return RedirectToAction(nameof(Index));
        }

        // Change Status Hiring Order And Sent Mail To Client Show Result.
        public async Task<IActionResult> EvaluationOrder(int Id, StatusHiringOrderEnum status)
        {
            var GetHiringOrd = await _HiringOrderService.ReturnHiringOrder(Id, status, UserId);
            if(!GetHiringOrd.IsValid)
            {
                //TempData["ResultEvaluOrdDanger"] = "لم يتم تغيير حالة الطلب بنجاح!";
                TempData["ResError"] = "e: لم يتم تغيير حالة الطلب بنجاح!";
                return RedirectToAction(nameof(Index)); 
            }
            TempData["ResError"] = "s: لقد تم تغيير حالة الطلب بنجاح!";

            var ArabicOrd = _HiringOrderService.ConvertOrederArabic(status);
            // Send Email To User
            var StatusSendMail = await _SendMailServices.SendMail("ahmadalmikkawi123@gmail.com",
                                     $"الرد على طلب {GetHiringOrd.OrderName}", $"لقد تم {ArabicOrd} طلبك.");  

            // Check If Email Sended Or Not
            if(StatusSendMail)
            {
                TempData["ResultEvaluOrdSuccess"] = "لقد تم إرسال إيميل للعميل بنتيجة التقييم بنجاح.";

            }
            else
            {
                TempData["ResultEvaluOrdDanger"] = "لم يتم إرسال إيميل للعميل بنتيجة التقييم لوجود مشكلة في بيانات العميل.";
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GetUsersApplyingOrder(int Id)
        {
            TempData["HiringOrderId"] = Id;
            var Users = await _HiringOrderService.GetUsersApplyingForOrder(Id);
            return View(Users);
        }

        // Evaluation Applicants From Orgnization Admin Accept Or Rejected
        public async Task<IActionResult> EvaluationApplicants(string UserId, int HiringOrdId, 
                                            StatusHiringOrderEnum status, string ViewName)
        {
            int num;
            var CurrentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if(TempData["HiringOrderId"] != null)
            {
                 num = (int)TempData["HiringOrderId"];
            }else
            {
                num = 0;
            }
            
            var EvalOrder = await _HiringOrderService.EvalApplicatin(UserId, HiringOrdId, status, CurrentUserId);
            TempData["ResError"] = "s: لقد تم تغيير حالة الطلب بنجاح!";

            var ArabicOrd = _HiringOrderService.ConvertOrederArabic(status);
            // Send Email To User
            var StatusSendMail = await _SendMailServices.SendMail("ahmadalmikkawi123@gmail.com",
                 $"الرد على وظيفة {EvalOrder.HiringOrder.Title}",
                 $"مرحباً عزيزي / {EvalOrder.User.FullName} لقد تم {ArabicOrd} طلبك في وظيفة {EvalOrder.HiringOrder.Title}");

            // Check If Email Sended Or Not
            if (StatusSendMail)
            {
                TempData["ResultEvaluOrdSuccessMain"] = "s:لقد تم إرسال إيميل للعميل بنتيجة التقييم بنجاح.";

            }
            else
            {
                TempData["ResultEvaluOrdDangerMain"] = "s:لم يتم إرسال إيميل للعميل بنتيجة التقييم لوجود مشكلة في بيانات العميل.";
            }
            switch(ViewName)
            {
                case "GetUsersApplyingOrder":
                    return RedirectToAction("GetUsersApplyingOrder", new { Id = num });
                case "DisplayEvalOrdToOrg":
                    return RedirectToAction("DisplayEvalOrdToOrg");
                case "DisplayNotEvalOrdToOrg":
                    return RedirectToAction("DisplayNotEvalOrdToOrg");
                case "AllHiringOrderUserToAdmin":
                    return RedirectToAction("AllHiringOrderUserToAdmin");
                default:
                    return Redirect("~/Home/Index");
            }
            
        }

        // Dispaly All Evaluation HiringOrders To Current Orgnization
        public async Task<IActionResult> DisplayEvalOrdToOrg ()
        {
            TempData["TitleView"] = "الطلبات المقيَّمة";
            TempData["TypeView"] = 1;
            var CurrentUser = await _IUserServices.ReturnUser(UserId);
            var GetOrders = await _HiringOrderService.EvalApplicatin((int)CurrentUser.NumOrgnization);
            return View(GetOrders);
        }

        // Dispaly All Not Evaluation HiringOrders To Current Orgnization
        public async Task<IActionResult> DisplayNotEvalOrdToOrg()
        {
            TempData["TitleView"] = "الطلبات الغير مقيَّمة";
            TempData["TypeView"] = 2;
            var CurrentUser = await _IUserServices.ReturnUser(UserId);
            var GetOrders = await _HiringOrderService.NotEvalApplicatin((int)CurrentUser.NumOrgnization);
            return View("DisplayEvalOrdToOrg", GetOrders);
        }

        // **************** Start DashBoard To Current Orgnization **************** :
        public async Task<IActionResult> DashBoardOrgnization()
        {
            var CurrentUser = await _IUserServices.ReturnUser(UserId);
            return View(_HiringOrderService.DashBoardOrgnization((int)CurrentUser.NumOrgnization));
        }

        public async Task<IActionResult> EvalHiringOrderByAdmin()
        {
            var CurrentUser = await _IUserServices.ReturnUser(UserId);
            return Ok(_HiringOrderService.EvalHiringOrderByAdmin((int)CurrentUser.NumOrgnization));
        }

FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Controllers/UserController.cs
using AutoMapper;
using HiringWeb.Core.DTO;
using HiringWeb.Core.ViewModels;
using HiringWeb.DataBase.Models;
using HiringWeb.Services.NotificationsOperations;
using HiringWeb.Services.OrgnizationOperations;
using HiringWeb.Services.UserOperations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Hiring.Web_FinalProject_VisionPlus_ASP.NetCore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : BaseController
    {
        private readonly IUserServices _IUserServices;
        private readonly IOrgnizationServices _OrgServices;
        private readonly IMapper _Mapper;
        private readonly SignInManager<UserApplication> _SignInManager;



        public UserController(IUserServices IUserServices,
                              IOrgnizationServices OrgServices,
                              SignInManager<UserApplication> SignInManager,
                              IMapper Mapper, IUserServices UserOperation,
                              INotificationServices INotificationServices) : base(UserOperation, INotificationServices)
        {
            _IUserServices = IUserServices;
            _OrgServices = OrgServices;
            _Mapper = Mapper;
            _SignInManager = SignInManager;
        }
        public async Task<IActionResult> Index(int Id, string SearchWord, int SelectSize)
        {
            var AllUser = await _IUserServices.Index(Id, SearchWord, SelectSize);
            ViewBag.SearchWord = SearchWord;
            ViewBag.SelectSize = SelectSize;
            return View(AllUser);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var users = await _IUserServices.AddGet();
            return View(users);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Add([FromForm] ErrorUserAddPostViewModel model, IFormFile ProfileImage)
        {
            //Save Image(File) In DB
            if (ProfileImage != null)
            {
                using (var fileStore = new MemoryStream())
                {
                    await ProfileImage.CopyToAsync(fileStore);
                    model.UserCreateDto.ProfileImgUser = fileStore.ToArray();
                }
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            var SentModel = await _IUserServices.AddPost(model.UserCreateDto, userId);
            if (!SentModel.IsFalid)
            {
                //ViewBag.ResError = SentModel.ResultError;
                TempData["ResError"] = $"e: {SentModel.ResultError}";
                return View(SentModel);
            }
            TempData["ResError"] = $"s: لقد تم إضافة المستخدم بنجاح.";
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                // To SingnIn User After register And Return Home Page With Login
               await _SignInManager
              .PasswordSignInAsync(model.UserCreateDto.Email, model.UserCreateDto.Password, false, false);
                return Redirect("~/Home/Index");
            }

        }

        [HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {
            var GetModel = await _IUserServices.EditGet(Id);
            if (!GetModel.IsFalid)
            {
                return NotFound();
            }
            return View(GetModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] ErrorUserAddPostViewModel model, IFormFile ProfileImage)
        {
            ErrorOrgnizeEdit ModelOrg = new ErrorOrgnizeEdit();
            ErrorUserAddPostViewModel ModelUser = new ErrorUserAddPostViewModel();
            if (ProfileImage != null)
            {
                using (var fileStore = new MemoryStream())
                {
                    await ProfileImage.CopyToAsync(fileStore);
                    model.UserCreateDto.ProfileImgUser = fileStore.ToArray();
                }
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId

            if (model.UserCreateDto.NumOrgnization != null)
            {
                var NewModel = new OrgnizationEditDto
                {
                    Email = model.UserCreateDto.Email,
                    FullName = model.UserCreateDto.FullName,
                    ProfileImgUser = model.UserCreateDto.ProfileImgUser,
                    PhoneNumber = model.UserCreateDto.PhoneNumber,
                    AllRoles = model.UserCreateDto.AllRoles,
                    Id = (int)model.UserCreateDto.NumOrgnization
                };
                ModelOrg = await _OrgServices.EditPost(NewModel, userId);
                ModelUser.IsFalid = true;
            }
            else
            {
                ModelUser = await _IUserServices.EditPost(model.UserCreateDto, userId);
                ModelOrg.IsFalid = true;
            }


            if (!ModelOrg.IsFalid)
            {
                //ViewBag.ResError = ModelOrg.ResultError;
                TempData["ResError"] = $"e: {ModelOrg.ResultError}";
                return View(ModelOrg);
            }
            else if (!ModelUser.IsFalid)
            {
                //ViewBag.ResError = ModelOrg.ResultError;
                TempData["ResError"] = $"e: {ModelUser.ResultError}";

                return View(ModelUser);
            }

            TempData["ResError"] = $"s: لقد تم تعديل المستخدم بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string Id)
        {
            var GetUser = await _IUserServices.ReturnUser(Id);
            if (GetUser.NumOrgnization != null)
            {
                TempData["ResError"] = $"e:عزيزي لا يمكن حذف هذا المستخدم لأنه مدير شركة، يجب حذف شركته ثم حذفه!";
                return RedirectToAction(nameof(Index));
            }


            var SetModel = await _IUserServices.Delete(Id);
            if (!SetModel.IsValid)
            {
                return NotFound();
            }
            TempData["ResError"] = "s:لقد تم حذف المستخدم بنجاح.";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Excel()
        {
            var content = await _IUserServices.ToExcel();

            return File(
               content,
               "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
               $"{"report"}-{DateTime.Now:d}.xlsx"
           );
        }



    }
}

FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Views/Notifications/NotificateAdminJobEval.cshtml
@model HiringOrderDetailsViewModel
@{
    ViewData["Title"] = "تفاصيل الطلب";
    int Counter = 0;
}

<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h2 class="card-label" data-aos="fade-left">
                <span class="d-block pt-5 font-size-h2-lg">تفاصيل الطلب</span>
            </h2>
        </div>
    </div>
    <hr />
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped"
                   style=" border: 5px solid #788da3; text-align: center; background: #1f518fad;">
                <thead style="background: #a94442; color: #eee038f2; font-size: 27px;">
                    <tr>
                        <td>العنوان</td>
                        <td>التفاصيل</td>
                    </tr>
                </thead>

                <tbody>
                    <tr data-aos="fade-left">
                        <td>اسم الوظيفة</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>حالة الوظيفة</td>
                        <td>@Model.OrderStatus</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>تاريخ نشر الوظيفة</td>
                        <td>@Model.CreateAt.ToString("yyyy-MM-dd")</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>وقت انتهاء التقدم</td>
                        <td>@Model.Deadline.ToString("yyyy-MM-dd")</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>اسم الشركة</td>
                        <td>@Model.Orgnization.Name</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>البريد الالكتروني للشركة</td>
                        <td>@Model.Orgnization.Email</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>جوال الشركة</td>
                        <td>@Model.Orgnization.PhoneNumber</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>عنوان الشركة</td>
                        <td>@Model.Orgnization.Address</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>المرفقات</td>

                        @if (Model.AllAttachments.Count > 0)
                        {
                            <td>
                                <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="MenuProcess" data-bs-toggle="dropdown" aria-expanded="false">
                                        عرض المرفقات
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="MenuProcess" style="padding:10px;">
                                        @foreach (var file in Model.AllAttachments)
                                        {
                                            Counter++;
                                            <li>
                                                <a target="_blank" href="~/AllFiles/@file.AttachmentUrl" style="color:black">إضغط لعرض مرفق @Counter</a>
                                            </li>

                                        }
                                    </ul>
                                </div>
                            </td>

                        }
                        else
                        {
                            <td>لا يوجد مرفقات</td>
                        }

                    </tr>

                </tbody>
            </table>
        </div>
        <div class="form-group col-md-12" data-aos="fade-left">
            @if (Model.OrderStatus == StatusHiringOrderEnum.Pending)
            {

                <a class="btn btn-primary" href="~/HiringOrder/EvaluationOrder?Id=@Model.Id
                  &status=@StatusHiringOrderEnum.Approved">
                    قبول
                </a>


                <a class="btn btn-primary" href="~/HiringOrder/EvaluationOrder?Id=@Model.Id
                  &status=@StatusHiringOrderEnum.Rejected">
                    رفض
                </a>

            }
            else if (Model.OrderStatus == StatusHiringOrderEnum.Approved)
            {
                <a class="btn btn-primary" href="~/HiringOrder/EvaluationOrder?Id=@Model.Id
                  &status=@StatusHiringOrderEnum.Rejected">
                    رفض
                </a>
            }
            else if (Model.OrderStatus == StatusHiringOrderEnum.Rejected)
            {
                <a class="btn btn-primary" href="~/HiringOrder/EvaluationOrder?Id=@Model.Id
                  &status=@StatusHiringOrderEnum.Approved">
                    قبول
                </a>
            }
            <div><a asp-action="Index" asp-controller="HiringOrder" class="btn btn-primary mt-2">الرجوع للوظائف</a></div>
        </div>
    </div>
</div>

FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Views/Notifications/NotificateAdminNewUser.cshtml
@model HiringWeb.Core.ModelaDB.UserApplicationViewModel
@{
    ViewData["Title"] = "تفاصيل المستخدم";
}

<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h2 class="card-label" data-aos="fade-left">
                <span class="d-block pt-5 font-size-h2-lg">تفاصيل المستخدم</span>
            </h2>
        </div>
    </div>
    <hr />
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped"
                   style=" border: 5px solid #788da3; text-align: center; background: #1f518fad;">
                <thead style="background: #a94442; color: #eee038f2; font-size: 27px;">
                    <tr>
                        <td>العنوان</td>
                        <td>التفاصيل</td>
                    </tr>
                </thead>

                <tbody>
                    <tr data-aos="fade-left">
                        <td>اسم المستخدم</td>
                        <td>@Model.FullName</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>البريد الالكتروني</td>
                        <td>@Model.Email</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>رقم جوال</td>
                        <td>@Model.PhoneNumber</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>السيرة الذاتية</td>
                        <td><a target="_blank" href="~/AllFiles/@Model.Cv" style="color:black;">إضغط لعرض CV</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="form-group col-md-12" data-aos="fade-left">
            <div><a asp-action="Index" asp-controller="User" class="btn btn-primary mt-2">الرجوع للمستخدمين</a></div>
        </div>
    </div>
</div>

FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Views/Notifications/NotificateDetailsApplicant.cshtml
@model NotificateDetailsApplicantViewModel
@{
    ViewData["Title"] = "تفاصيل الطلب";
}

<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h2 class="card-label" data-aos="fade-left">
                <span class="d-block pt-5 font-size-h2-lg">تفاصيل الطلب</span>
            </h2>
        </div>
    </div>
    <hr />
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped"
                   style=" border: 5px solid #788da3; text-align: center; background: #1f518fad;">
                <thead style="background: #a94442; color: #eee038f2; font-size: 27px;">
                    <tr>
                        <td>العنوان</td>
                        <td>التفاصيل</td>
                    </tr>
                </thead>
                <tbody>
                    <tr data-aos="fade-left">
                        <td>اسم الوظيفة</td>
                        <td>@Model.HiringOrder.Title</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>تقييم الطلب</td>
                        <td>@Model.StatusType</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>وقت التقدم</td>
                        <td>@Model.CreateAt.ToString("yyyy-MM-dd")</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>الراتب</td>
                        <td>@Model.HiringOrder.Salary</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>الشركة المتقدم لها</td>
                        <td>@Model.HiringOrder.Orgnization.Name</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>بريد الشركة</td>
                        <td>@Model.HiringOrder.Orgnization.Email</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>جوال الشركة</td>
                        <td>@Model.HiringOrder.Orgnization.PhoneNumber</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>عنوان الشركة</td>
                        <td>@Model.HiringOrder.Orgnization.Address</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="form-group col-md-12" data-aos="fade-left">
            <a asp-action="DisAllHiringOrderCurrUser" asp-controller="HiringOrder" class="btn btn-primary">الرجوع للوظائف</a>
        </div>
    </div>
</div>

FinalProject_HiringWeb/Hiring.Web_FinalProject_VisionPlus_ASP.NetCore/Views/Notifications/NotificateOrgJobEval.cshtml
@model HiringOrderDetailsViewModel
@{
    ViewData["Title"] = "تفاصيل الطلب";
}

<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h2 class="card-label" data-aos="fade-left">
                <span class="d-block pt-5 font-size-h2-lg">تفاصيل الطلب</span>
            </h2>
        </div>
    </div>
    <hr />
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped"
                   style=" border: 5px solid #788da3; text-align: center; background: #1f518fad;">
                <thead style="background: #a94442; color: #eee038f2; font-size: 27px;">
                    <tr>
                        <td>العنوان</td>
                        <td>التفاصيل</td>
                    </tr>
                </thead>

                <tbody>
                    <tr data-aos="fade-left">
                        <td>اسم الوظيفة</td>
                        <td>@Model.Title</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>حالة الوظيفة</td>
                        <td>@Model.OrderStatus</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>التقييم بواسطة</td>
                        <td>مشرف الموقع</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>تاريخ نشر الوظيفة</td>
                        <td>@Model.CreateAt.ToString("yyyy-MM-dd")</td>
                    </tr>
                    <tr data-aos="fade-left">
                        <td>وقت انتهاء التقدم</td>
                        <td>@Model.Deadline.ToString("yyyy-MM-dd")</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="form-group col-md-12" data-aos="fade-left">
            <div><a asp-action="Index" asp-controller="HiringOrder" class="btn btn-primary mt-2">الرجوع للوظائف</a></div>
        </div>
    </div>
</div>